# Linting workflow triggered when PR is opened
name: code checking

# run on pull request
on:
  pull_request:
    branches:
      - main

# run install and lint steps without makefile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Lint using flake8 and black
        run: |
          flake8 .
          black --check .
